### ISSUE TITLE
Delete Sample

### ISSUE THREAD

**Issue by Element115sw** [bhowiebkr/laser-level-webcam#10]
When the last point at the end has been measured and another measurement is triggered accidentally all the measurements have to be done again because there are to many samples now and there is no ability to delete a sample 

A button to delete a sample would be helpful.

**Comment by bhowiebkr** [comment]
I'll see if I can add a button to do that so you can delete a sample outright as replacing it doesn't help you in that case.

**Comment by bhowiebkr** [comment]
Added a delete button now:
https://github.com/bhowiebkr/laser-level-webcam/commit/52498e93ebde3a88d81155bf5963a3fe50893a29
