### ISSUE TITLE
Error when running on Apple Silicon

### ISSUE THREAD

**Issue by nanoplane** [bhowiebkr/laser-level-webcam#11]
not running (camera view is all black) when running on Apple Silicon with the cheap camera I bought.. Camera works on other apps, but not on laser-level...  I get the following error in the terminal:
Videotoolbox desn't support cvPixelFormat: 2037741171 "yuvs"  Camera pix format: Format_YUYV

**Comment by bhowiebkr** [comment]
Looks to be the camera pixel format being the issue. I've never heard of YUVS before. YUV is common. Not sure what the S stands for. I'll see if I can make sense of it tonight.

**Comment by nanoplane** [comment]
Weird thing is tha it works fine on my intel MacBook Pro

**Comment by nanoplane** [comment]
Also works fine running on Windows 11 (under Parallels) on my M2Max MBPro... but not under Mac OS on the same machine.. I suspect it's a code version thing..

**Comment by bhowiebkr** [comment]
I have no way of testing it on apple silicon. It is most likely related to it being incompatible with QT which is what the tool is built with. I would suggest stick with intel/amd based machines to use this tool
