### ISSUE TITLE
Alternative setting for scale, other than sensor size

### ISSUE THREAD

**Issue by besenyeim** [bhowiebkr/laser-level-webcam#13]
It is difficult to measure sensor width precisely, so an alternative method to set resolution is needed.
Comparing measurements to a known reference seems to be a good one. E.g. gauge blocks, or a linear guide and a sensitive dial indicator.

For this, it can be useful to switch to display raw pixel count, instead of mm/thou. (I guess, that's enough at first, user can calculate sensor size from that.)

This may be duplicate to #7 , but that doesn't have description, so IDK.

**Comment by bhowiebkr** [comment]
They way I would suggest setting the sensor size is like this:

- Either look up the sensor datasheet which will give you accurate measurements. Most likely the measurement will be in metric if the webcam is made in china.

- Take a top-down photo of the circuit board, measure the circuit board width using calipers than in some imaging software measure the zoomed in photo of the image sensor’s size and calculate it by using the measurement with calipers as a reference (measure the pixels of the sensor to the circuit board)
