### ISSUE TITLE
"Device Settings" button does nothing

### ISSUE THREAD

**Issue by besenyeim** [bhowiebkr/laser-level-webcam#14]
Windows, V0.3.2, .exe downloaded from Releases.

**Comment by bhowiebkr** [comment]
This calls the device settings from FFMPEG which gives an easy way to access the low level settings of the webcam device. In order for you to get that button working you’ll need to have FFMPEG installed and part of your windows path for the tool to call it. I might look at seeing if there is a way to call it directly with python but sofar doesn’t look easy.

**Comment by bhowiebkr** [comment]
I've added a popup message if the tool finds that you are missing FFMPEG. If you are missing it, you'll need to download, install and add it to your Windows path

https://github.com/bhowiebkr/laser-level-webcam/commit/e7a95af343b90876f2093dd62f4cf54025ec7bc0
