### ISSUE TITLE
Awesome tool but not working on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by Ali-Ozkan1** [bhowiebkr/laser-level-webcam#17]
Hello, I saw your tool on Youtube and I wanted to try it on ubuntu. But I could not start  the program whatever I did.
I've created virtual enviroment but I couldnt activate because of missing script for debian based systems.
If you have time, can you provide nessecary scripts for debian based systems?
Thanks

**Comment by bhowiebkr** [comment]
Post the error you are getting. 

You should be able to run the tool from source by following the instructions in the readme. See Build from source

**Comment by Ali-Ozkan1** [comment]
I've follow instruction from readme.

i've created virtual enviroment as venv according to instruction. But when I tried to activate using the script from venv/bin/activate, activate script says "You must source this script: $ source activate"
I've sourced and still get the same error.

**Comment by bhowiebkr** [comment]
I think you are running into the issue of activating the venv on Linux as the command you run is different than on Windows. See https://www.w3docs.com/snippets/python/how-to-activate-virtualenv-in-linux.html

**Comment by Ali-Ozkan1** [comment]
Hello again and thanks for taking time.
Right now virtualenviroment activated. But new error code is:
"qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, minimal, vkkhrdisplay, wayland, offscreen, linuxfb, minimalegl, wayland-egl, xcb, vnc.
Aborted (core dumped)
"
All packages are installed on my system.

**Comment by bhowiebkr** [comment]
I've had the xcb problem before on Ubuntu. It's a Linux component missing. 

Running this command should fix it

sudo apt-get install --reinstall libxcb-xinerama0

Found at https://askubuntu.com/questions/308128/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without

**Comment by Ali-Ozkan1** [comment]
Thanks for the help and thanks for this great tool.
