### ISSUE TITLE
What to name it?

### ISSUE THREAD

**Issue by bhowiebkr** [bhowiebkr/laser-level-webcam#2]
I should probably rename this repo because it's confusing to people thinking that a laser-level or much of anything todo with levelling is what this repo is about. The name originates because I used a laser level and a webcam as the hardware. 

A laser source preferably as a projected very straight line makes for the ideal emitter for the image sensor. I’m currently working on such a custom hardware device. 

Any ideas on the repo name are welcome.

**Comment by furynick** [comment]
a bit late but you may replace "level" by "flatness" in the name.
