### ISSUE TITLE
When outlier removal percentage is small calculation fails

### ISSUE THREAD

**Issue by asteppke** [bhowiebkr/laser-level-webcam#4]
When the outlier removal percentage is small and not many samples are taken then the calculation of the mean fails. 

Looking a bit why this occurs in this case `n_outliers` is zero and the sample array gets truncated to an empty array.

**Comment by bhowiebkr** [comment]
fixed in [[#5 #](https://github.com/bhowiebkr/laser-level-webcam/commit/528295297a56709864d36ea80017c2f9f24b1bca)](https://github.com/bhowiebkr/laser-level-webcam/commit/528295297a56709864d36ea80017c2f9f24b1bca)
