### ISSUE TITLE
Export to Excel / Measuring more than one line

### ISSUE THREAD

**Issue by GvTT** [bhowiebkr/laser-level-webcam#6]
Hello Bryan,

wonderful tool. I just got everything running today...
after modifying a web-cam and building a base I installed the pyton sources. 
Crazy how sensitive all this is. I can see a clear influence by just adding 15g to the base of the camera, when it is sitting on my desk.

Below you find my remarks and request for an array scan rather than a single line scan...
Not being familiar with Git I hope that I filed this at the right place. 

Many greetings and thanks for sharing
Georg

----------------------------------------

Following your description I have following remarks:
- use **CMD -> as administrator** to call pip for the requirements
- I also had to install ffmpeg
- on my computer the paths to pip and ffmpeg hat to be added manually

-----------------------------------------

Trying the tool, I did not find a way to copy the measurements to the clipboard for further processing (csv works but is less convenient). I want to scan 2 or more lines (2 rails of a lathe, the table of a milling machine or my reference plate (600x400mm granite)). This would be a nice addition.

-----------------------------------------

I also suggest 2 additional buttons:
"track heat up" = take measurements every 20s... to monitor the thermal heat-up till stability 
"clear array" = to remove all measurement points

------------------------------------------

May I suggest alternative names for the columns "scraping // shimming" (even if these are clear after reading the description):
- above min
- below max

-------------------------------------------

Α compile failed with Python 3.12, downloading the precompiled windows zip fails due to warning as well...
...but this is already addressed in another issue

**Comment by bhowiebkr** [comment]
Thanks for all the suggestions, I'll put them on the list of things to improve the tool.

**Comment by bhowiebkr** [comment]
Going through things. I'll hold off on getting Python 3.12 working until it's out of [prerelease](https://www.python.org/download/pre-releases/)

**Comment by bhowiebkr** [comment]
> May I suggest alternative names for the columns "scraping // shimming" (even if these are clear after reading the description):
> 
>     * above min
> 
>     * below max

I've changed to display that way. Makes more sense https://github.com/bhowiebkr/laser-level-webcam/commit/5b835dda000c4ce35dfa3146d709897beb8e68cf
